In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5,6,7,78,0]

In [3]:
np.array(my_list)

array([ 1,  2,  3,  4,  5,  6,  7, 78,  0])

In [4]:
type(np.array(my_list))

numpy.ndarray

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([ 1,  2,  3,  4,  5,  6,  7, 78,  0])

In [7]:
np.arange(0, 10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,11,100)

array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
        0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ,
        1.11111111,  1.22222222,  1.33333333,  1.44444444,  1.55555556,
        1.66666667,  1.77777778,  1.88888889,  2.        ,  2.11111111,
        2.22222222,  2.33333333,  2.44444444,  2.55555556,  2.66666667,
        2.77777778,  2.88888889,  3.        ,  3.11111111,  3.22222222,
        3.33333333,  3.44444444,  3.55555556,  3.66666667,  3.77777778,
        3.88888889,  4.        ,  4.11111111,  4.22222222,  4.33333333,
        4.44444444,  4.55555556,  4.66666667,  4.77777778,  4.88888889,
        5.        ,  5.11111111,  5.22222222,  5.33333333,  5.44444444,
        5.55555556,  5.66666667,  5.77777778,  5.88888889,  6.        ,
        6.11111111,  6.22222222,  6.33333333,  6.44444444,  6.55555556,
        6.66666667,  6.77777778,  6.88888889,  7.        ,  7.11111111,
        7.22222222,  7.33333333,  7.44444444,  7.55555556,  7.66

In [12]:
np.random.randint(0,1000)

408

In [13]:
np.random.randint(0,1000,(3,3))

array([[238, 229, 358],
       [303, 305, 694],
       [715, 262, 628]])

In [14]:
np.random.normal(0,10)

8.326795592409733

In [15]:
np.random.seed(101)
np.random.randint(0,1000,10)

array([863, 523, 337, 838, 575, 599,  75, 393, 973, 552])

In [16]:
np.random.seed(10)
np.random.randint(0,1000,10)

array([265, 125, 996, 527, 320, 369, 123, 156, 985, 733])

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7, 78,  0])

In [18]:
arr.max()

78

In [19]:
arr.min()

0

In [20]:
arr.mean()

11.777777777777779

In [21]:
arr.argmax()

7

In [22]:
arr.argmin()

8

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7, 78,  0])

In [24]:
arr.reshape(10,100)

ValueError: cannot reshape array of size 9 into shape (10,100)

In [25]:
mat = np.arange(0,100).reshape(10,10)

In [26]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [27]:
mat[0,1]

1

In [28]:
mat[6,6]

66

In [29]:
mat[:,0]

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [30]:
mat[:,1]

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [33]:
mat[5,:]

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59])

In [39]:
mat[0:3, 0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [40]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [41]:
mat < 50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [42]:
my_filter = mat > 50

In [45]:
mat[my_filter]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])