In [1]:
import tensorflow as tf

In [2]:
tf.compat.v1.disable_eager_execution()

In [3]:
print(tf.__version__)

2.0.0-alpha0


In [4]:
hello = tf.constant("hello")

In [5]:
world = tf.constant(" world")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [8]:
# with tf.Session() as sess:
#     result = sess.run(hello+world)

    
sess = tf.compat.v1.Session()
result = sess.run(hello + world)

In [9]:
print(result)

b'hello world'


In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [12]:
type(a)

tensorflow.python.framework.ops.Tensor

In [13]:
a +b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [14]:
a +b 

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [15]:
b +a

<tf.Tensor 'add_3:0' shape=() dtype=int32>

In [16]:
tf.compat.v1.disable_eager_execution()
sess = tf.compat.v1.Session()


In [17]:
result = sess.run(a + b)

In [18]:
result

30

In [19]:
const = tf.constant(10)

In [20]:
fill_mat = tf.fill((4,4),10)

In [21]:
myzeros = tf.zeros((4,4))

In [22]:
myones = tf.ones((4,4))

In [23]:
myrandn = tf.random.normal((4,4),mean=0, stddev=1.0)

In [24]:
myrandu = tf.random.uniform((4,4),minval=0, maxval=1)

In [25]:
myzeros

<tf.Tensor 'zeros:0' shape=(4, 4) dtype=float32>

In [26]:
myones

<tf.Tensor 'ones:0' shape=(4, 4) dtype=float32>

In [27]:
myrandn

<tf.Tensor 'random_normal:0' shape=(4, 4) dtype=float32>

In [28]:
myrandu

<tf.Tensor 'random_uniform:0' shape=(4, 4) dtype=float32>

In [29]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [30]:
sess=tf.compat.v1.InteractiveSession()
# sess = tf.InteractiveSession()

In [31]:
for op in my_ops:
#     print(sess.run(op))
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.24535115 -0.333911   -0.28955775 -0.04673018]
 [-1.2081108  -1.7855577  -0.82014394  0.5392376 ]
 [ 1.1585984   2.0786295   0.4120864   0.3104735 ]
 [ 0.2661707   2.3617034  -0.47055775  0.7421676 ]]


[[0.88277686 0.62169445 0.5620899  0.96610355]
 [0.13786697 0.01527715 0.24913979 0.4259056 ]
 [0.45406878 0.01526618 0.3438604  0.4013139 ]
 [0.24973512 0.20076072 0.50170004 0.5094112 ]]




In [32]:
a = tf.constant([
    [1,2],
    [3,4]
])

In [33]:
a.get_shape()

TensorShape([2, 2])

In [34]:
b = tf.constant([
    [10],
    [100]
])

In [35]:
b.get_shape()

TensorShape([2, 1])

In [36]:
result = tf.matmul(a,b)

In [37]:
sess.run(result)

array([[210],
       [430]])

In [38]:
result.eval()

array([[210],
       [430]])